// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Presupuestos.Infrastructure.Data;

#nullable disable

namespace Presupuestos.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Presupuestos.Domain.Models.Budget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("BenefitPercentage")
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("ClientAddress")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientEmail")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientPhone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DollarRate")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("FeesCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<bool>("IncludeFees")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeLabor")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("LaborCost")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("Name");

                    b.ToTable("Budgets", (string)null);
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.BudgetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BudgetId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LaborItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LaborItemName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("LaborQuantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PriceARS")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("PriceUSD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid?>("SubgroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubgroupName")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BudgetId");

                    b.HasIndex("Type");

                    b.ToTable("BudgetItems", (string)null);
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.ExchangeRateRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuoteCurrency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,8)");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("BaseCurrency", "QuoteCurrency");

                    b.ToTable("ExchangeRates", (string)null);
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.LaborCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LaborCategories", (string)null);
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.LaborItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceARS")
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("LaborItems", (string)null);
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceUSD")
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.ToTable("Materials", (string)null);
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.Subgroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Subgroups", (string)null);
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.SubgroupMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceUSD")
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,6)");

                    b.Property<Guid>("SubgroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubgroupId");

                    b.ToTable("SubgroupMaterials", (string)null);
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.Budget", b =>
                {
                    b.OwnsOne("Presupuestos.Domain.Models.BudgetTaxes", "Taxes", b1 =>
                        {
                            b1.Property<Guid>("BudgetId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("BankFees")
                                .HasColumnType("decimal(9,4)");

                            b1.Property<decimal>("IB")
                                .HasColumnType("decimal(9,4)");

                            b1.Property<decimal>("IC")
                                .HasColumnType("decimal(9,4)");

                            b1.Property<decimal>("IG")
                                .HasColumnType("decimal(9,4)");

                            b1.Property<decimal>("IVA")
                                .HasColumnType("decimal(9,4)");

                            b1.Property<decimal>("IVAT")
                                .HasColumnType("decimal(9,4)");

                            b1.Property<bool>("IncludeTaxes")
                                .HasColumnType("INTEGER");

                            b1.HasKey("BudgetId");

                            b1.ToTable("Budgets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BudgetId");
                        });

                    b.Navigation("Taxes")
                        .IsRequired();
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.BudgetItem", b =>
                {
                    b.HasOne("Presupuestos.Domain.Models.Budget", null)
                        .WithMany("Items")
                        .HasForeignKey("BudgetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.LaborItem", b =>
                {
                    b.HasOne("Presupuestos.Domain.Models.LaborCategory", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.SubgroupMaterial", b =>
                {
                    b.HasOne("Presupuestos.Domain.Models.Subgroup", null)
                        .WithMany("Materials")
                        .HasForeignKey("SubgroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.Budget", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.LaborCategory", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Presupuestos.Domain.Models.Subgroup", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
